[theme]
base="light"
primaryColor="#0D47A1"            # Deep Blue
backgroundColor="#FFFFFF"         # White
secondaryBackgroundColor="#E3F2FD" # Light Blue for cards/sections
textColor="#0D47A1"               # Blue text
font="sans serif"
